### ISSUE TITLE
Entity is marked as invalid when it has one character

### ISSUE THREAD

**Issue by saroup** [microsoft/NLU.DevOps#202]
We currently only support that startPos < endPos. However, if the entity is one character then the startPos is equal endPos.

**Comment by rozele** [comment]
Ah, just change https://github.com/microsoft/NLU.DevOps/blob/56d4bb47e56e46e3cc8ca92883655a1c54ffeba2/src/NLU.DevOps.Core/LabeledUtteranceConverter.cs#L126 to `<=` and add a unit test.

**Comment by saroup** [comment]
doing that as we speak :)
